export const COUNTRY_FALLBACK: Record<string, string> = {
  italy: "rome",
  japan: "tokyo",
  france: "paris",
  spain: "barcelona",
  thailand: "bangkok",
  indonesia: "bali",
  australia: "sydney",
  singapore: "singapore",
  "south korea": "seoul",
  korea: "seoul",
  malaysia: "kuala lumpur",
  "hong kong": "hong kong",
  vietnam: "ho chi minh city",
  taiwan: "taipei",
  china: "shanghai",
  "united kingdom": "london",
  uk: "london",
  england: "london",
  usa: "new york",
  "united states": "new york",
  america: "new york",
  canada: "vancouver",
  brazil: "rio de janeiro",
  "new zealand": "auckland",
  newzealand: "auckland",
  uae: "dubai",
  "united arab emirates": "dubai",
  turkey: "istanbul",
  switzerland: "zurich",
  netherlands: "amsterdam",
  germany: "berlin",
  austria: "vienna",
  portugal: "lisbon",
  greece: "athens",
  philippines: "manila",
};