export const CITY_PATHS: Record<string, string> = {
  // ASIA
  singapore: "https://au.trip.com/hotels/singapore-hotels-list-73/",
  "hong kong": "https://au.trip.com/hotels/hong-kong-hotels-list-58/",
  tokyo: "https://au.trip.com/hotels/tokyo-hotels-list-228/",
  osaka: "https://au.trip.com/hotels/osaka-hotels-list-219/",
  kyoto: "https://au.trip.com/hotels/kyoto-hotels-list-430/",
  seoul: "https://au.trip.com/hotels/seoul-hotels-list-274/",
  bangkok: "https://au.trip.com/hotels/bangkok-hotels-list-359/",
  phuket: "https://au.trip.com/hotels/phuket-hotels-list-725/",
    bali: "https://au.trip.com/hotels/bali-hotels-list-723/",
  jakarta: "https://au.trip.com/hotels/jakarta-hotels-list-524/",
  bandung: "https://au.trip.com/hotels/bandung-hotels-list-740/",
  surabaya: "https://au.trip.com/hotels/surabaya-hotels-list-1244/",
  medan: "https://au.trip.com/hotels/medan-hotels-list-1389/",
  "kuala lumpur": "https://au.trip.com/hotels/kuala-lumpur-hotels-list-315/",
  penang: "https://au.trip.com/hotels/penang-hotels-list-1378/",
  langkawi: "https://au.trip.com/hotels/langkawi-hotels-list-1225/",
  "ho chi minh city": "https://au.trip.com/hotels/ho-chi-minh-city-hotels-list-301/",
  hanoi: "https://au.trip.com/hotels/hanoi-hotels-list-286/",
  "da nang": "https://au.trip.com/hotels/da-nang-hotels-list-1356/",
  "hoi an": "https://au.trip.com/hotels/hoi-an-hotels-list-1775/",
  "nha trang": "https://au.trip.com/hotels/nha-trang-hotels-list-1777/",
  "phu quoc": "https://au.trip.com/hotels/phu-quoc-island-hotels-list-5649/",
  taipei: "https://au.trip.com/hotels/taipei-hotels-list-360/",
  shanghai: "https://au.trip.com/hotels/shanghai-hotels-list-2/",
  beijing: "https://au.trip.com/hotels/beijing-hotels-list-1/",
  dubai: "https://au.trip.com/hotels/dubai-hotels-list-220/",
  istanbul: "https://au.trip.com/hotels/istanbul-hotels-list-168/",
  manila: "https://au.trip.com/hotels/manila-hotels-list-364/",

  // EUROPE
  paris: "https://au.trip.com/hotels/paris-hotels-list-192/",
  rome: "https://au.trip.com/hotels/rome-hotels-list-343/",
  milan: "https://au.trip.com/hotels/milan-hotels-list-361/",
  naples: "https://au.trip.com/hotels/naples-hotels-list-1262/",
  barcelona: "https://au.trip.com/hotels/barcelona-hotels-list-110/",
  london: "https://au.trip.com/hotels/london-hotels-list-269/",
  amsterdam: "https://au.trip.com/hotels/amsterdam-hotels-list-57/",
  zurich: "https://au.trip.com/hotels/zurich-hotels-list-384/",
  berlin: "https://au.trip.com/hotels/berlin-hotels-list-306/",
  vienna: "https://au.trip.com/hotels/vienna-hotels-list-651/",
  lisbon: "https://au.trip.com/hotels/lisbon-hotels-list-1231/",
  athens: "https://au.trip.com/hotels/athens-hotels-list-710/",
  florence: "https://au.trip.com/hotels/florence-hotels-list-687/",
  venice: "https://au.trip.com/hotels/venice-hotels-list-688/",
  santorini: "https://au.trip.com/hotels/santorini-hotels-list-3571/",
  mykonos: "https://au.trip.com/hotels/mykonos-hotels-list-4228/",

  // AUSTRALIA / NZ
  sydney: "https://au.trip.com/hotels/sydney-hotels-list-501/",
  melbourne: "https://au.trip.com/hotels/melbourne-hotels-list-358/",
  brisbane: "https://au.trip.com/hotels/brisbane-hotels-list-680/",
  "gold coast": "https://au.trip.com/hotels/gold-coast-hotels-list-1210/",
  perth: "https://au.trip.com/hotels/perth-hotels-list-681/",
  adelaide: "https://au.trip.com/hotels/adelaide-hotels-list-1245/",
  auckland: "https://au.trip.com/hotels/auckland-hotels-list-678/",
  queenstown: "https://au.trip.com/hotels/queenstown-hotels-list-1993/",

  // USA / CANADA
  "new york": "https://au.trip.com/hotels/new-york-hotels-list-248/",
  "los angeles": "https://au.trip.com/hotels/los-angeles-hotels-list-347/",
  "las vegas": "https://au.trip.com/hotels/las-vegas-hotels-list-400/",
  orlando: "https://au.trip.com/hotels/orlando-hotels-list-1187/",
  miami: "https://au.trip.com/hotels/miami-hotels-list-1922/",
  honolulu: "https://au.trip.com/hotels/honolulu-hotels-list-757/",
  chicago: "https://au.trip.com/hotels/chicago-hotels-list-549/",
  "san francisco": "https://au.trip.com/hotels/san-francisco-hotels-list-313/",
  vancouver: "https://au.trip.com/hotels/vancouver-hotels-list-476/",
  toronto: "https://au.trip.com/hotels/toronto-hotels-list-311/",

  // SOUTH AMERICA
  "rio de janeiro": "https://au.trip.com/hotels/rio-de-janeiro-hotels-list-769/",
  "sao paulo": "https://au.trip.com/hotels/sao-paulo-hotels-list-301/",
};