import { createSupabaseServerClient } from "@/lib/supabase/server";
import type { Metadata } from "next";

export async function generateMetadata({
  params,
}: {
  params: { slug: string };
}): Promise<Metadata> {
  const supabase = createSupabaseServerClient();

  const { data: trip } = await supabase
    .from("itineraries")
    .select("title, destination, budget")
    .eq("slug", params.slug)
    .maybeSingle();

  if (!trip) {
    return {
      title: "Trip not found | Itenora",
      description: "Shared itinerary page on Itenora.",
    };
  }

  return {
    title: `${trip.title} | Itenora`,
    description: `AI-generated ${trip.budget ?? ""} itinerary for ${trip.destination}. View this shared trip and plan your own with Itenora.`,
    openGraph: {
      title: `${trip.title} | Itenora`,
      description: `AI-generated itinerary for ${trip.destination}.`,
      url: `${process.env.NEXT_PUBLIC_SITE_URL}/trips/share/${params.slug}`,
      siteName: "Itenora",
      type: "article",
    },
    twitter: {
      card: "summary_large_image",
      title: `${trip.title} | Itenora`,
      description: `AI-generated itinerary for ${trip.destination}.`,
    },
  };
}

export default async function PublicTripPage({
  params,
}: {
  params: { slug: string };
}) {
  const supabase = createSupabaseServerClient();

  const { data: trip } = await supabase
    .from("itineraries")
    .select("*")
    .eq("slug", params.slug)
    .maybeSingle();

  if (!trip) {
    return (
      <div className="max-w-4xl mx-auto p-10">
        <h1 className="text-2xl font-bold">Trip not found</h1>
      </div>
    );
  }

  const { data: relatedTrips } = await supabase
    .from("itineraries")
    .select("slug, title")
    .eq("destination", trip.destination)
    .neq("slug", params.slug)
    .limit(5);

  const itinerary = trip.generated_plan?.itinerary || [];

  const structuredData = {
    "@context": "https://schema.org",
    "@type": "TravelItinerary",
    name: trip.title,
    description: `AI-generated itinerary for ${trip.destination}`,
    url: `${process.env.NEXT_PUBLIC_SITE_URL}/trips/share/${params.slug}`,
    itinerary: itinerary.map((day: any) => ({
      "@type": "ListItem",
      name: `Day ${day.day} - ${day.theme}`,
      description: day.stops
        ?.map((stop: any) => `${stop.time} ${stop.title}`)
        .join(", "),
    })),
  };

  return (
    <div className="max-w-4xl mx-auto p-10 space-y-10">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(structuredData),
        }}
      />

      <h1 className="text-4xl font-bold">{trip.title}</h1>

      <p className="text-gray-600">Destination: {trip.destination}</p>

      {itinerary.map((day: any) => (
        <div key={day.day} className="border rounded-xl p-6 space-y-4">
          <h2 className="text-2xl font-semibold">
            Day {day.day} — {day.theme}
          </h2>

          <div className="space-y-2">
            {day.stops.map((stop: any, i: number) => (
              <div key={i} className="flex gap-4">
                <div className="font-mono text-sm text-gray-500">
                  {stop.time}
                </div>

                <div>
                  <div className="font-medium">{stop.title}</div>

                  {stop.notes && (
                    <div className="text-sm text-gray-500">{stop.notes}</div>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      ))}

      {relatedTrips && relatedTrips.length > 0 && (
        <div className="border-t pt-10">
          <h2 className="mb-4 text-2xl font-semibold">
            More {trip.destination} itineraries
          </h2>

          <ul className="space-y-2">
            {relatedTrips.map((r: any) => (
              <li key={r.slug}>
                <a
                  href={`/trips/share/${r.slug}`}
                  className="text-blue-600 hover:underline"
                >
                  {r.title}
                </a>
              </li>
            ))}
          </ul>
        </div>
      )}

      <div className="border-t pt-10 text-center">
        <p className="text-gray-600">
          ✨ This itinerary was generated by Itenora AI
        </p>

        <a
          href="/"
          className="inline-block mt-4 rounded-xl bg-black px-6 py-3 text-white"
        >
          Plan your own trip
        </a>
      </div>
    </div>
  );
}